cep.window.seconds=120
cep.state.ttl.minutes=30

cep.high-frequency.threshold=3
cep.high-frequency.amount-min=50000000

cep.declined-burst.threshold=3

cep.rapid-micropayments.threshold=3
cep.rapid-micropayments.amount-min=2000
cep.rapid-micropayments.amount-max=10000
