apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: DS_CLICKHOUSE
    isDefault: true
    editable: true
    jsonData:
      server: clickhouse
      port: 9000
      username: default
      defaultDatabase: fraud_detection
      protocol: native

  - name: Prometheus
    type: prometheus
    uid: DS_PROMETHEUS
    url: http://prometheus:9090
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s
